modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://example.com/issues"

[[mods]]
modId="lvlcap"
version="${file.jarVersion}"
displayName="Pixelmon Level Cap"
displayURL="https://example.com/"
logoFile=""
credits=""
authors="sidemodsrerforged"
description='''
Adds dynamic Pokemon level caps to Pixelmon gyms.
'''

[[dependencies.lvlcap]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.lvlcap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="SERVER"

[[dependencies.lvlcap]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.0.0,)"
    ordering="NONE"
    side="SERVER"
